name: Update CodeChef Stats

on:
  schedule:
    - cron: '0 3 * * *'   # runs daily at 3 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate badge
        run: python update_codechef_stats.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add codechef_stats.svg
          git commit -m "Update CodeChef stats" || echo "No changes"
          git push
